_BASE_: base.yaml
MODEL:
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
  MASK_FORMER:
    TRAIN_NUM_POINTS: 50000
    MASK_WEIGHT: 15.0
    DICE_WEIGHT: 6.0
    SIZE_DIVISIBILITY: 1
    TEST:
      SEMANTIC_ON: True
INPUT:
  IMAGE_SIZE: 448
  MIN_SIZE_TEST: 448
  MAX_SIZE_TEST: 448
  SIZE_DIVISIBILITY: 1
SOLVER:
  WARMUP_ITERS: 2000
  AMP:
    ENABLED: True
    DTYPE: "bfloat16"
